name: ServerVerse
version: '${project.version}'
main: net.ethanburkett.serververse.mc1_20_1
api-version: '1.20'
commands:
  verify:
    description: Verify access from ServerVerse
    usage: /verify <given token>
    permission: serververse.verify